# Generated by Django 4.1.5 on 2023-10-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='bookimage/'),
        ),
    ]
