# Generated by Django 4.1.5 on 2023-10-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Novels', 'Novels'), ('Comics', 'Comics'), ('Biography', 'Biography'), ('Horror', 'Horror'), ('Others', 'Others')], default='Fiction', max_length=20),
        ),
    ]
